### ISSUE TITLE
Rendering with shadow

### ISSUE THREAD

**Issue by staceycy** [airalcorn2/strike-with-a-pose#12]
Hi, 

Thank you very much for your awesome work. 

I am trying to use your render scripts to render some objects onto RGB image. I noticed that the 'DirLight' setting in your code can make the rendered objects brighter. I want to ask is it possible to create shadow for the rendered objects? Or are there any resources that can help to achieve this?  

Looking forward to your reply. 

Thanks
Stacey

**Comment by airalcorn2** [comment]
Anything you can do in OpenGL you can do with ModernGL, so it is possible, but it would take a non-trivial amount of work. I don't have time for that at the moment, but [this tutorial](https://learnopengl.com/Advanced-Lighting/Shadows/Shadow-Mapping) describes how to implement shadow mapping in OpenGL. It's what I would use if I were going to try to implement it myself.

**Comment by staceycy** [comment]
@airalcorn2 Thank you very much for your kind suggestion. I will try it 😄
