### ISSUE TITLE
Release of the 30 Objects Dataset?

### ISSUE THREAD

**Issue by averysi224** [airalcorn2/strike-with-a-pose#17]
Hi Michael,

I found your paper while I was exploring adversarial behavior attack ideas and really enjoy your paper! It is concise and very comprehensive. I'm thinking of doing some experiments on your work. May I ask if it is possible that you release the whole 30 3D objects dataset?

Thanks!
Wenwen

**Comment by airalcorn2** [comment]
Thank you for the kind words, Wenwen. The 3D objects we used in the paper are proprietary (we purchased them), and so we do not have the rights to share them. [This spreadsheet](https://docs.google.com/spreadsheets/d/1ykLwrK98jg3128UjlKx22vvuuNTSHPUuBMf3cOPd6Tg/edit?usp=sharing) contains the URLs for where each object can be purchased.
